name: Config-Server
on:
  workflow_dispatch: 
  push:
    branches: ['main']
    paths: ['samples/config-server/**']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/config-server

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: 17
          cache: maven
      - name: Log into container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        run: |
          (cd samples/config-server && ./mvnw spring-boot:build-image -Dspring-boot.build-image.publish=true -Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }})
